In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, cross_val_score, ShuffleSplit

In [3]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=.3)

**Logistic Regression**

In [5]:
lr = LogisticRegression(solver='lbfgs', max_iter=100000, multi_class='auto')
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [6]:
lr_score = lr.score(X_test, y_test)
lr_score

0.9555555555555556

**Support Vector Machine**

In [7]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [8]:
svm_score = svm.score(X_test, y_test)
svm_score

0.40925925925925927

**Random Forest**

In [9]:
rf = RandomForestClassifier(n_estimators=10)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [10]:
rf_score = rf.score(X_test, y_test)
rf_score

0.9407407407407408

In [11]:
print('Logistic Regression {} Support Vector Machine {} Random Forest {}'.format(lr_score, svm_score, rf_score))

Logistic Regression 0.9555555555555556 Support Vector Machine 0.40925925925925927 Random Forest 0.9407407407407408


# Score Function

In [27]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

# KFold Cross Validation
**Basic**

In [40]:
kf = KFold(n_splits=3)

In [41]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [46]:
model_lr = LogisticRegression(solver='lbfgs', max_iter=10000, multi_class='auto')
model_svm = SVC(gamma='auto')
model_rf = RandomForestClassifier(n_estimators=40)

score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    score_lr.append(get_score(model_lr, X_train, X_test, y_train, y_test))    
    score_svm.append(get_score(model_svm, X_train, X_test, y_train, y_test))
    score_rf.append(get_score(model_rf, X_train, X_test, y_train, y_test))
    

In [47]:
score_lr

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [48]:
score_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [49]:
score_rf

[0.9248747913188647, 0.9432387312186978, 0.9181969949916527]

# StratifiedKFold Cross Validation
**Basic**

In [50]:
skf = StratifiedKFold(n_splits=3)

In [51]:
score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in skf.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    score_lr.append(get_score(model_lr, X_train, X_test, y_train, y_test))    
    score_svm.append(get_score(model_svm, X_train, X_test, y_train, y_test))
    score_rf.append(get_score(model_rf, X_train, X_test, y_train, y_test))

In [52]:
score_lr

[0.925249169435216, 0.9382303839732888, 0.9228187919463087]

In [53]:
score_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [54]:
score_rf

[0.925249169435216, 0.9332220367278798, 0.9211409395973155]

# cross_val_score function

In [67]:
cross_val_score(model_lr, digits.data, digits.target, cv=3)

array([0.92524917, 0.93823038, 0.92281879])

In [69]:
cross_val_score(model_svm, digits.data, digits.target, cv = 3)

array([0.39368771, 0.41068447, 0.45973154])

In [68]:
cross_val_score(model_rf, digits.data, digits.target, cv = 3)

array([0.9269103 , 0.95158598, 0.9261745 ])